pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["definitions.htm","Definitions","Modular Application Framework Components Definitions Top Previous Next This section contains definitions for expressions used in the help file. (c...",""],
["definitions_dft.htm","DFT","Modular Application Framework Components DFT Top Previous Next The DFT (Dynamic Function Table) contains all code links in a MAF based application...",""],
["definitions_dynamicfunction.htm","DynamicFunction","Modular Application Framework Components DynamicFunction Top Previous Next A DynamicFunction is basically represented by its ID (HookID) and conta...",""],
["definitions_hook.htm","Hook","Modular Application Framework Components Hook Top Previous Next See DynamicFunction . (c)opyright 2009 by Helge Lange. All Rights Reserved. ",""],
["definitions_subhook.htm","SubHook","Modular Application Framework Components SubHook Top Previous A SubHook defines a single function in a module. It is a member to one DynamicFuncti...",""],
["deployment.htm","Deployment","Modular Application Framework Components Deployment Top Previous Next MAF Applications and all modules always have to be built with runtime packag...",""],
["getting_support.htm","Getting Support","Modular Application Framework Components Getting Support Top Previous Next There are several support options available This help file and the web ...",""],
["introduction.htm","Overview","Modular Application Framework Components Overview Top Next Modular Application Framework Components (MAF Components) is a suite of components to b...",""],
["reference.htm","Reference","Modular Application Framework Components Reference Top Previous Next This topic describes the MAF component classes. Manager Components Manager co...",""],
["tmafdatastorage.htm","TmafDataStorage","Modular Application Framework Components TmafDataStorage Top Previous Next TmafManagerLoader class overview Properties Name Description BaseDB The...",""],
["tmafdatastorage_events.htm","Events","Modular Application Framework Components Events Top Previous Next Enter topic text here. (c)opyright 2009 by Helge Lange. All Rights Reserved. ",""],
["tmafdatastorage_methods.htm","Methods","Modular Application Framework Components Methods Top Previous Next Enter topic text here. (c)opyright 2009 by Helge Lange. All Rights Reserved. ",""],
["tmafdatastorage_properties.htm","Properties","Modular Application Framework Components Properties Top Previous Next Enter topic text here. (c)opyright 2009 by Helge Lange. All Rights Reserved. ",""],
["tmafdatastorage_types.htm","Types","Modular Application Framework Components Types Top Previous Next Enter topic text here. (c)opyright 2009 by Helge Lange. All Rights Reserved. ",""],
["tmafhooclient.htm","TmafHookClient","Modular Application Framework Components TmafHookClient Top Previous Next The TmafHookClient ist actually used to connect to several Manager-Compo...",""],
["tmafhooclient_executehook.htm","ExecuteHook","Modular Application Framework Components ExecuteHook Top Previous Next Executes a DynamicFunction or a specific SubHook. Executing a specific SubH...",""],
["tmafhookclient_events.htm","Events","Modular Application Framework Components Events Top Previous Next Enter topic text here. (c)opyright 2009 by Helge Lange. All Rights Reserved. ",""],
["tmafhookclient_methods.htm","Methods","Modular Application Framework Components Methods Top Previous Next Methods used by the component TmafHookClient . Methods Name Description Execute...",""],
["tmafhookclient_onfunctionobserver.htm","OnFunctionObserver","Modular Application Framework Components OnFunctionObserver Top Previous Next Event will be fired, if the current TmafHooClient is observing one o...",""],
["tmafhookclient_properties.htm","Properties","Modular Application Framework Components Properties Top Previous Next Enter topic text here. (c)opyright 2009 by Helge Lange. All Rights Reserved. ",""],
["tmafhookclient___delete_functionobserver.htm","__Delete_FunctionObserver","Modular Application Framework Components __Delete_FunctionObserver Top Previous Next Deletes an previously installed observer for a DynamicFunctio...",""],
["tmafhookclient___query_hookmanager.htm","__Query_HookManager","Modular Application Framework Components __Query_HookManager Top Previous Next Executes a query to the TmafHookManager API. Class TmafHookClient S...",""],
["tmafhookclient___query_manager.htm","__Query_Manager","Modular Application Framework Components __Query_Manager Top Previous Next Executes a query to a manager API. Class TmafHookClient Syntax function...",""],
["tmafhookmanager.htm","TmafHookManager","Modular Application Framework Components TmafHookManager Top Previous Next TmafManagerLoader class overview Properties Name Description BaseDB The...",""],
["tmafhookmanager_overview.htm","Overview","Modular Application Framework Components Overview Top Previous Next The TmafHookManager manages all published code with a MAF-Application. To do t...",""],
["tmafhookmanager_properties.htm","Properties","Modular Application Framework Components Properties Top Previous Next Enter topic text here. (c)opyright 2009 by Helge Lange. All Rights Reserved. ",""],
["tmafhookmanager_types.htm","Types","Modular Application Framework Components Types Top Previous Next Enter topic text here. (c)opyright 2009 by Helge Lange. All Rights Reserved. ",""],
["tmafhoookclient___add_functionobserver.htm","__Add_FunctionObserver","Modular Application Framework Components __Add_FunctionObserver Top Previous Next Adds an observer to a DynamicFunction to get informed about chan...",""],
["tmaflinkmanager.htm","TmafLinkManager","Modular Application Framework Components TmafLinkManager Top Previous Next TmafLinkManager class overview Properties Name Description ModuleContro...",""],
["tmaflinkmanager_properties.htm","Properties","Modular Application Framework Components Properties Top Previous Next Enter topic text here. (c)opyright 2009 by Helge Lange. All Rights Reserved. ",""],
["tmaflinkmanager_types.htm","Types","Modular Application Framework Components Types Top Previous Next Enter topic text here. (c)opyright 2009 by Helge Lange. All Rights Reserved. ",""],
["tmafmanagerloader.htm","TmafManagerLoader","Modular Application Framework Components TmafManagerLoader Top Previous Next TmafManagerLoader class overview Properties Name Description AutoLoad...",""],
["tmafmanagerloader_addmanager.htm","AddManager","Modular Application Framework Components AddManager Top Previous Next Adds a manager to the internal manager list. Class TmafManagerLoader Syntax ...",""],
["tmafmanagerloader_afterconnect.htm","AfterConnect","Modular Application Framework Components AfterConnect Top Previous Next Fired after a manager was connected. Class TmafManagerLoader Syntax proper...",""],
["tmafmanagerloader_autoload.htm","AutoLoad","Modular Application Framework Components AutoLoad Top Previous Next Defines if the component loads and connects automatically to the manager defin...",""],
["tmafmanagerloader_beforeconnect.htm","BeforeConnect","Modular Application Framework Components BeforeConnect Top Previous Next Fired before the component connects to a manager. Class TmafManagerLoader...",""],
["tmafmanagerloader_beforeloadingmanager.htm","BeforeLoadingManager","Modular Application Framework Components BeforeLoadingManager Top Previous Next Fired before the component starts to connect to all manager regist...",""],
["tmafmanagerloader_classes.htm","Classes","Modular Application Framework Components Classes Top Previous Next Enter topic text here. (c)opyright 2009 by Helge Lange. All Rights Reserved. ",""],
["tmafmanagerloader_classes_inisettings.htm","INISettings","Modular Application Framework Components INISettings Top Previous Next Enter topic text here. (c)opyright 2009 by Helge Lange. All Rights Reserved. ",""],
["tmafmanagerloader_classes_registrysettings.htm","RegistrySettings","Modular Application Framework Components RegistrySettings Top Previous Next Enter topic text here. (c)opyright 2009 by Helge Lange. All Rights Res...",""],
["tmafmanagerloader_connectmanager.htm","ConnectManager","Modular Application Framework Components ConnectManager Top Previous Next Connects all manager registered at the moment. Class TmafManagerLoader S...",""],
["tmafmanagerloader_dataloadmethod.htm","DataLoadMethod","Modular Application Framework Components DataLoadMethod Top Previous Next Defines the method from where the information about the manager to load ...",""],
["tmafmanagerloader_deletemanager.htm","DeleteManager","Modular Application Framework Components DeleteManager Top Previous Next Deletes a manager entry from the internal manager list. Class TmafManager...",""],
["tmafmanagerloader_disconnectmanager.htm","DisconnectManager","Modular Application Framework Components DisconnectManager Top Previous Next Disconnects all manager connected at the moment. Class TmafManagerLoa...",""],
["tmafmanagerloader_events.htm","Events","Modular Application Framework Components Events Top Previous Next Events used by the component TmafManagerLoader . Events Name Description AfterCo...",""],
["tmafmanagerloader_inisettings.htm","INISettings","Modular Application Framework Components INISettings Top Previous Next Enter topic text here. (c)opyright 2009 by Helge Lange. All Rights Reserved. ",""],
["tmafmanagerloader_manager.htm","Manager","Modular Application Framework Components Manager Top Previous Next Enter topic text here. (c)opyright 2009 by Helge Lange. All Rights Reserved. ",""],
["tmafmanagerloader_managerloaderoptions.htm","ManagerLoaderOptions","Modular Application Framework Components ManagerLoaderOptions Top Previous Next Enter topic text here. (c)opyright 2009 by Helge Lange. All Rights...",""],
["tmafmanagerloader_managersubdirectory.htm","ManagerSubDirectory","Modular Application Framework Components ManagerSubDirectory Top Previous Next Enter topic text here. (c)opyright 2009 by Helge Lange. All Rights ...",""],
["tmafmanagerloader_methods.htm","Methods","Modular Application Framework Components Methods Top Previous Next Methods used by the component TmafManagerLoader . Methods Name Description AddM...",""],
["tmafmanagerloader_onconnect.htm","OnConnect","Modular Application Framework Components OnConnect Top Previous Next Fired when the component were able to connect successfully to a manager. Clas...",""],
["tmafmanagerloader_ondataload.htm","OnDataLoad","Modular Application Framework Components OnDataLoad Top Previous Next Disconnects all manager connected at the moment. Class TmafManagerLoader Syn...",""],
["tmafmanagerloader_ondisconnect.htm","OnDisconnect","Modular Application Framework Components OnDisconnect Top Previous Next Disconnects all manager connected at the moment. Class TmafManagerLoader S...",""],
["tmafmanagerloader_onloadingfinished.htm","OnLoadingFinished","Modular Application Framework Components OnLoadingFinished Top Previous Next Disconnects all manager connected at the moment. Class TmafManagerLoa...",""],
["tmafmanagerloader_onloadmanagererror.htm","OnLoadManagerError","Modular Application Framework Components OnLoadManagerError Top Previous Next Disconnects all manager connected at the moment. Class TmafManagerLo...",""],
["tmafmanagerloader_properties.htm","Properties","Modular Application Framework Components Properties Top Previous Next Properties used by the component TmafManagerLoader . Types Name Description ...",""],
["tmafmanagerloader_registrysettings.htm","RegistrySettings","Modular Application Framework Components RegistrySettings Top Previous Next Enter topic text here. (c)opyright 2009 by Helge Lange. All Rights Res...",""],
["tmafmanagerloader_tmanagernotify.htm","TManagerNotify","Modular Application Framework Components TManagerNotify Top Previous Next Enter topic text here. (c)opyright 2009 by Helge Lange. All Rights Reser...",""],
["tmafmanagerloader_types.htm","Types","Modular Application Framework Components Types Top Previous Next Types used by the component TmafManagerLoader . Types Name Description TManagerNo...",""],
["tmafmodulecontroller.htm","TmafModuleController","Modular Application Framework Components TmafModuleController Top Previous Next The TmafModuleController manages code within a module and must be ...",""],
["tmafmodulecontroller_events.htm","Events","Modular Application Framework Components Events Top Previous Next BeforeFormCreate (c)opyright 2009 by Helge Lange. All Rights Reserved. ",""],
["tmafmodulecontroller_events_beforeformcreate.htm","BeforeFormCreate","Modular Application Framework Components BeforeFormCreate Top Previous Next Fired before a form is created by the TmafModuleController. Obviously ...",""],
["tmafresourcemanager.htm","TmafResourceManager","Modular Application Framework Components TmafResourceManager Top Previous Next TmafManagerLoader class overview Properties Name Description FileRe...",""],
["tmafresourcemanager_events.htm","Events","Modular Application Framework Components Events Top Previous Next Enter topic text here. (c)opyright 2009 by Helge Lange. All Rights Reserved. ",""],
["tmafresourcemanager_methods.htm","Methods","Modular Application Framework Components Methods Top Previous Next Enter topic text here. (c)opyright 2009 by Helge Lange. All Rights Reserved. ",""],
["tmafresourcemanager_properties.htm","Properties","Modular Application Framework Components Properties Top Previous Next Enter topic text here. (c)opyright 2009 by Helge Lange. All Rights Reserved. ",""],
["tmafresourcemanager_types.htm","Types","Modular Application Framework Components Types Top Previous Next Enter topic text here. (c)opyright 2009 by Helge Lange. All Rights Reserved. ",""],
["tmafwindowmanager.htm","TmafWindowManager","Modular Application Framework Components TmafWindowManager Top Previous Next TmafManagerLoader class overview Properties Name Description ModuleCo...",""],
["tmafwindowmanager_events.htm","Events","Modular Application Framework Components Events Top Previous Next Enter topic text here. (c)opyright 2009 by Helge Lange. All Rights Reserved. ",""],
["tmafwindowmanager_methods.htm","Methods","Modular Application Framework Components Methods Top Previous Next Enter topic text here. (c)opyright 2009 by Helge Lange. All Rights Reserved. ",""],
["tmafwindowmanager_properties.htm","Properties","Modular Application Framework Components Properties Top Previous Next Enter topic text here. (c)opyright 2009 by Helge Lange. All Rights Reserved. ",""],
["tmafwindowmanager_types.htm","Types","Modular Application Framework Components Types Top Previous Next Enter topic text here. (c)opyright 2009 by Helge Lange. All Rights Reserved. ",""]];
